export const PUPIL_LOGIN_REQUEST = 'PUPIL_LOGIN_REQUEST'
export const PUPIL_LOGIN_SUCCESS = 'PUPIL_LOGIN_SUCCESS'
export const PUPIL_LOGIN_FAIL = 'PUPIL_LOGIN_FAIL'
export const PUPIL_LOGOUT = 'PUPIL_LOGOUT'


export const PUPIL_REGISTER_REQUEST = 'PUPIL_REGISTER_REQUEST'
export const PUPIL_REGISTER_SUCCESS = 'PUPIL_REGISTER_SUCCESS'
export const PUPIL_REGISTER_FAIL = 'PUPIL_REGISTER_FAIL'

export const PUPIL_DETAILS_REQUEST = 'PUPIL_DETAILS_REQUEST'
export const PUPIL_DETAILS_SUCCESS = 'PUPIL_DETAILS_SUCCESS'
export const PUPIL_DETAILS_FAIL = 'PUPIL_DETAILS_FAIL'
export const PUPIL_DETAILS_RESET = 'PUPIL_DETAILS_RESET'

export const PUPIL_UPDATE_PROFILE_REQUEST = 'PUPIL_UPDATE_PROFILE_REQUEST'
export const PUPIL_UPDATE_PROFILE_SUCCESS = 'PUPIL_UPDATE_PROFILE_SUCCESS'
export const PUPIL_UPDATE_PROFILE_FAIL = 'PUPIL_UPDATE_PROFILE_FAIL'
export const PUPIL_UPDATE_PROFILE_RESET = 'PUPIL_UPDATE_PROFILE_RESET'

export const PUPIL_LIST_REQUEST = 'PUPIL_LIST_REQUEST'
export const PUPIL_LIST_SUCCESS = 'PUPIL_LIST_SUCCESS'
export const PUPIL_LIST_FAIL = 'PUPIL_LIST_FAIL'

export const PUPIL_LIST_RESET = 'PUPIL_LIST_RESET'

export const PUPIL_DELETE_REQUEST = 'PUPIL_DELETE_REQUEST'
export const PUPIL_DELETE_SUCCESS = 'PUPIL_DELETE_SUCCESS'
export const PUPIL_DELETE_FAIL = 'PUPIL_DELETE_FAIL'

export const PUPIL_UPDATE_REQUEST = 'PUPIL_UPDATE_REQUEST'
export const PUPIL_UPDATE_SUCCESS = 'PUPIL_UPDATE_SUCCESS'
export const PUPIL_UPDATE_FAIL = 'PUPIL_UPDATE_FAIL'
export const PUPIL_UPDATE_RESET = 'PUPIL_UPDATE_RESET'