export const THEME_LIST_REQUEST = 'THEME_LIST_REQUEST'
export const THEME_LIST_SUCCESS = 'THEME_LIST_SUCCESS'
export const THEME_LIST_FAIL = 'THEME_LIST_FAIL'


export const THEME_DETAILS_REQUEST = 'THEME_DETAILS_REQUEST'
export const THEME_DETAILS_SUCCESS = 'THEME_DETAILS_SUCCESS'
export const THEME_DETAILS_FAIL = 'THEME_DETAILS_FAIL'
export const THEME_DETAILS_RESET = 'THEME_DETAILS_RESET'