export const TUTOR_LOGIN_REQUEST = 'TUTOR_LOGIN_REQUEST'
export const TUTOR_LOGIN_SUCCESS = 'TUTOR_LOGIN_SUCCESS'
export const TUTOR_LOGIN_FAIL = 'TUTOR_LOGIN_FAIL'
export const TUTOR_LOGOUT = 'TUTOR_LOGOUT'


export const TUTOR_REGISTER_REQUEST = 'TUTOR_REGISTER_REQUEST'
export const TUTOR_REGISTER_SUCCESS = 'TUTOR_REGISTER_SUCCESS'
export const TUTOR_REGISTER_FAIL = 'TUTOR_REGISTER_FAIL'

export const TUTOR_DETAILS_REQUEST = 'TUTOR_DETAILS_REQUEST'
export const TUTOR_DETAILS_SUCCESS = 'TUTOR_DETAILS_SUCCESS'
export const TUTOR_DETAILS_FAIL = 'TUTOR_DETAILS_FAIL'
export const TUTOR_DETAILS_RESET = 'TUTOR_DETAILS_RESET'

export const TUTOR_UPDATE_PROFILE_REQUEST = 'TUTOR_UPDATE_PROFILE_REQUEST'
export const TUTOR_UPDATE_PROFILE_SUCCESS = 'TUTOR_UPDATE_PROFILE_SUCCESS'
export const TUTOR_UPDATE_PROFILE_FAIL = 'TUTOR_UPDATE_PROFILE_FAIL'
export const TUTOR_UPDATE_PROFILE_RESET = 'TUTOR_UPDATE_PROFILE_RESET'

export const TUTOR_LIST_REQUEST = 'TUTOR_LIST_REQUEST'
export const TUTOR_LIST_SUCCESS = 'TUTOR_LIST_SUCCESS'
export const TUTOR_LIST_FAIL = 'TUTOR_LIST_FAIL'

export const TUTOR_LIST_RESET = 'TUTOR_LIST_RESET'

export const TUTOR_DELETE_REQUEST = 'TUTOR_DELETE_REQUEST'
export const TUTOR_DELETE_SUCCESS = 'TUTOR_DELETE_SUCCESS'
export const TUTOR_DELETE_FAIL = 'TUTOR_DELETE_FAIL'

export const TUTOR_UPDATE_REQUEST = 'TUTOR_UPDATE_REQUEST'
export const TUTOR_UPDATE_SUCCESS = 'TUTOR_UPDATE_SUCCESS'
export const TUTOR_UPDATE_FAIL = 'TUTOR_UPDATE_FAIL'
export const TUTOR_UPDATE_RESET = 'TUTOR_UPDATE_RESET'